# Generated by Django 3.1b1 on 2020-06-26 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresultdetails',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='testresultdetails',
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='avr_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
